### PR TITLE
3473 Added try/catch block and respond proper error event for duplicate quoteId usecase

### PR DESCRIPTION
**Pull request by myo-min-htet**

### CODE REVIEW

**Comment by jfantunes** [comment]
@myo-min-htet 
Seems good, nice catch.
Can you make the tests pass or do you want me to take a look?

**Comment by myo-min-htet** [comment]
> @myo-min-htet Seems good, nice catch. Can you make the tests pass or do you want me to take a look?

Do you want me to add a unit test case for that?
If so, I will create it.

**Comment by jfantunes** [comment]
> > @myo-min-htet Seems good, nice catch. Can you make the tests pass or do you want me to take a look?
> 
> Do you want me to add a unit test case for that? If so, I will create it.

@myo-min-htet 
Sorry, I thought the tests are broken when I saw the build failing.
The problem is this
image

If you click on the build detail, you see that we are getting a build error related to lint.
Usually, lint-related errors are easily fixed by running `npm run lint:fix`, but in this case, I think it's more related to the try-catch block.
Thank you

**Comment by myo-min-htet** [comment]
> > > @myo-min-htet Seems good, nice catch. Can you make the tests pass or do you want me to take a look?
> > 
> > 
> > Do you want me to add a unit test case for that? If so, I will create it.
> 
> @myo-min-htet Sorry, I thought the tests are broken when I saw the build failing. The problem is this image
> 
> If you click on the build detail, you see that we are getting a build error related to lint. Usually, lint-related errors are easily fixed by running `npm run lint:fix`, but in this case, I think it's more related to the try-catch block. Thank you

Hello @jfantunes , I just updated for lint issue. Please kindly check and review again.

**Comment by jfantunes** [comment]
> > > > @myo-min-htet Seems good, nice catch. Can you make the tests pass or do you want me to take a look?
> > > 
> > > 
> > > Do you want me to add a unit test case for that? If so, I will create it.
> > 
> > 
> > @myo-min-htet Sorry, I thought the tests are broken when I saw the build failing. The problem is this image
> > If you click on the build detail, you see that we are getting a build error related to lint. Usually, lint-related errors are easily fixed by running `npm run lint:fix`, but in this case, I think it's more related to the try-catch block. Thank you
> 
> Hello @jfantunes , I just updated for lint issue. Please kindly check and review again.

That seems nice, thank you @myo-min-htet.
Just one thing before I approve please resolve the conflicts with main branch as stated above.
image

Thank you

**Review by jfantunes — APPROVED** [review]

**Comment by pedrosousabarreto** [comment]
@myo-min-htet Was this completed?

**Comment by myo-min-htet** [comment]
[like]  Myo Min Htet reacted to your message:
________________________________

**Pull request merged**
